// manage_tool.go implements the capability_manage meta-tool (Phase A + Phase B).
//
// Phase A (read-only):
//   - tree:               View capability tree structure (subtree filter, depth control)
//   - inspect:            View single node metadata (all 7 dimensions)
//   - validate:           Three-level validation (L1 Node → L2 Cross-Node → L3 System)
//   - diagnose:           Drift diagnosis (tree vs 9 consumers)
//   - generate_prompt:    Generate prompt section for a given tier
//   - generate_allowlist: Generate tool allowlist for a given tier
//
// Phase B (P7, patch-based write paths):
//   - propose_register:   Propose registering a new tool node
//   - propose_update:     Propose updating node fields
//   - propose_routing:    Propose routing rule changes
//   - propose_binding:    Propose skill binding changes
//   - apply_patch:        Apply approved patch (requires exec_escalation)
//
// Design doc: docs/codex/2026-03-09-能力树与自治能力管理系统架构设计-v2.md §6
package capabilities

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
	"sync"
	"time"
)

// ---------------------------------------------------------------------------
// P4-1: Tool input/output types
// ---------------------------------------------------------------------------

// ManageInput is the input schema for the capability_manage tool.
type ManageInput struct {
	Action string `json:"action"` // tree|inspect|validate|diagnose|generate_prompt|generate_allowlist
	// tree/inspect params
	NodeID string `json:"node_id,omitempty"` // Node ID for inspect, subtree root for tree
	Depth  int    `json:"depth,omitempty"`   // Max depth for tree (0 = unlimited)
	// generate_prompt/generate_allowlist params
	Tier string `json:"tier,omitempty"` // Intent tier: greeting/question/task_light/task_write/task_delete/task_multimodal
	// validate params
	Level int `json:"level,omitempty"` // Validation level: 1/2/3 (0 = all levels)
	// P7: propose_register params
	NodeSpec *ProposeNodeSpec `json:"node_spec,omitempty"` // Node specification for propose_register
	// P7: propose_update/routing/binding params
	Updates json.RawMessage `json:"updates,omitempty"` // Partial fields to update
	// P7: apply_patch params
	PatchID  string `json:"patch_id,omitempty"` // Patch ID for apply_patch
	Approved bool   `json:"approved,omitempty"` // Approval flag for apply_patch (exec_escalation)
}

// ManageResult is the output of the capability_manage tool.
type ManageResult struct {
	Action  string      `json:"action"`
	Success bool        `json:"success"`
	Data    interface{} `json:"data,omitempty"`
	Error   string      `json:"error,omitempty"`
}

// ---------------------------------------------------------------------------
// P7-6: Patch diff format (simplified JSON Patch for capability tree)
// ---------------------------------------------------------------------------

// TreePatch represents a proposed change to the capability tree.
// Generated by propose_* actions, consumed by apply_patch.
type TreePatch struct {
	ID          string           `json:"id"`
	Action      string           `json:"action"` // "register"|"update"|"routing"|"binding"
	Description string           `json:"description"`
	Operations  []PatchOperation `json:"operations"`
	CreatedAt   string           `json:"created_at"`
	Status      string           `json:"status"` // "proposed"|"applied"
}

// PatchOperation is a single operation within a TreePatch.
type PatchOperation struct {
	Op    string          `json:"op"`              // "add"|"replace"|"remove"
	Path  string          `json:"path"`            // Node ID path (e.g., "fs/new_tool")
	Field string          `json:"field,omitempty"` // Sub-structure: "prompt"|"routing"|"skills"|etc.
	Value json.RawMessage `json:"value,omitempty"` // New value
	Old   json.RawMessage `json:"old,omitempty"`   // Previous value (informational)
}

// ProposeNodeSpec is the input for propose_register.
type ProposeNodeSpec struct {
	Name    string            `json:"name"`
	Parent  string            `json:"parent"`
	Kind    NodeKind          `json:"kind"`
	Runtime *NodeRuntime      `json:"runtime,omitempty"`
	Prompt  *NodePrompt       `json:"prompt,omitempty"`
	Routing *NodeRouting      `json:"routing,omitempty"`
	Perms   *NodePermissions  `json:"perms,omitempty"`
	Skills  *NodeSkillBinding `json:"skills,omitempty"`
	Display *NodeDisplay      `json:"display,omitempty"`
	Policy  *NodePolicy       `json:"policy,omitempty"`
}

// ---------------------------------------------------------------------------
// P7: In-memory patch store
// ---------------------------------------------------------------------------

var (
	patchStore   = make(map[string]*TreePatch)
	patchStoreMu sync.RWMutex
)

func storePatch(p *TreePatch) {
	patchStoreMu.Lock()
	defer patchStoreMu.Unlock()
	patchStore[p.ID] = p
}

func loadPatch(id string) *TreePatch {
	patchStoreMu.RLock()
	defer patchStoreMu.RUnlock()
	return patchStore[id]
}

func nextPatchID() string {
	return fmt.Sprintf("patch-%d", time.Now().UnixNano())
}

// ClearPatchStoreForTesting resets the patch store. Test-only.
func ClearPatchStoreForTesting() {
	patchStoreMu.Lock()
	defer patchStoreMu.Unlock()
	patchStore = make(map[string]*TreePatch)
}

// ---------------------------------------------------------------------------
// P4-1: Dispatch entry point
// ---------------------------------------------------------------------------

// ExecuteManageTool dispatches a capability_manage tool call.
// Phase A actions are read-only; Phase B propose_* generate diffs without
// modifying state; apply_patch modifies the in-memory tree (requires approval).
func ExecuteManageTool(inputJSON json.RawMessage) (string, error) {
	var input ManageInput
	if err := json.Unmarshal(inputJSON, &input); err != nil {
		return formatManageError("", fmt.Sprintf("invalid input: %v", err)), nil
	}

	tree := DefaultTree()

	var result ManageResult
	switch input.Action {
	case "tree":
		result = executeManageTree(tree, input)
	case "inspect":
		result = executeManageInspect(tree, input)
	case "validate":
		result = executeManageValidate(tree, input)
	case "diagnose":
		result = executeManageDiagnose(tree)
	case "generate_prompt":
		result = executeManageGeneratePrompt(tree, input)
	case "generate_allowlist":
		result = executeManageGenerateAllowlist(tree, input)
	// P7: write-path actions
	case "propose_register":
		result = executeManageProposeRegister(tree, input)
	case "propose_update":
		result = executeManageProposeUpdate(tree, input)
	case "propose_routing":
		result = executeManageProposeRouting(tree, input)
	case "propose_binding":
		result = executeManageProposeBinding(tree, input)
	case "apply_patch":
		result = executeManageApplyPatch(tree, input)
	default:
		return formatManageError(input.Action, fmt.Sprintf("unknown action %q; valid actions: tree, inspect, validate, diagnose, generate_prompt, generate_allowlist, propose_register, propose_update, propose_routing, propose_binding, apply_patch", input.Action)), nil
	}

	data, err := json.MarshalIndent(result, "", "  ")
	if err != nil {
		return formatManageError(input.Action, fmt.Sprintf("marshal result: %v", err)), nil
	}
	return string(data), nil
}

func formatManageError(action, msg string) string {
	r := ManageResult{Action: action, Success: false, Error: msg}
	data, _ := json.MarshalIndent(r, "", "  ")
	return string(data)
}

// ---------------------------------------------------------------------------
// P4-2: action=tree — View capability tree structure
// ---------------------------------------------------------------------------

// TreeNodeView is a compact view of a tree node for the tree action.
type TreeNodeView struct {
	ID       string          `json:"id"`
	Name     string          `json:"name"`
	Kind     NodeKind        `json:"kind"`
	MinTier  string          `json:"min_tier,omitempty"`
	Summary  string          `json:"summary,omitempty"`
	Dynamic  bool            `json:"dynamic,omitempty"`
	Children []*TreeNodeView `json:"children,omitempty"`
}

func executeManageTree(tree *CapabilityTree, input ManageInput) ManageResult {
	if input.NodeID != "" {
		// Subtree mode
		root := tree.Lookup(input.NodeID)
		if root == nil {
			return ManageResult{Action: "tree", Success: false, Error: fmt.Sprintf("node %q not found", input.NodeID)}
		}
		view := buildTreeView(tree, root, input.Depth, 0)
		return ManageResult{Action: "tree", Success: true, Data: view}
	}

	// Full tree: build from root children
	var roots []*TreeNodeView
	for _, id := range tree.RootChildren {
		node := tree.Nodes[id]
		if node == nil {
			continue
		}
		roots = append(roots, buildTreeView(tree, node, input.Depth, 0))
	}
	return ManageResult{Action: "tree", Success: true, Data: roots}
}

func buildTreeView(tree *CapabilityTree, node *CapabilityNode, maxDepth, currentDepth int) *TreeNodeView {
	view := &TreeNodeView{
		ID:   node.ID,
		Name: node.Name,
		Kind: node.Kind,
	}
	if node.Routing != nil && node.Routing.MinTier != "" {
		view.MinTier = node.Routing.MinTier
	}
	if node.Prompt != nil && node.Prompt.Summary != "" {
		view.Summary = node.Prompt.Summary
	}
	if node.Runtime != nil && node.Runtime.Dynamic {
		view.Dynamic = true
	}

	// Recurse into children (depth-limited)
	if maxDepth > 0 && currentDepth >= maxDepth {
		return view
	}
	for _, childID := range node.Children {
		child := tree.Nodes[childID]
		if child == nil {
			continue
		}
		view.Children = append(view.Children, buildTreeView(tree, child, maxDepth, currentDepth+1))
	}
	return view
}

// ---------------------------------------------------------------------------
// P4-3: action=inspect — View single node metadata (7 dimensions)
// ---------------------------------------------------------------------------

func executeManageInspect(tree *CapabilityTree, input ManageInput) ManageResult {
	if input.NodeID == "" {
		return ManageResult{Action: "inspect", Success: false, Error: "node_id is required for inspect action"}
	}
	node := tree.Lookup(input.NodeID)
	if node == nil {
		// Try lookup by name
		node = tree.LookupByName(input.NodeID)
	}
	if node == nil {
		return ManageResult{Action: "inspect", Success: false, Error: fmt.Sprintf("node %q not found", input.NodeID)}
	}
	return ManageResult{Action: "inspect", Success: true, Data: node}
}

// ---------------------------------------------------------------------------
// P4-4: action=validate — Three-level validation
// ---------------------------------------------------------------------------

// ValidationIssue represents a single validation finding.
type ValidationIssue struct {
	Level   int    `json:"level"`   // 1, 2, or 3
	NodeID  string `json:"node_id"` // Affected node (empty for L3 system issues)
	Message string `json:"message"`
}

// ValidationResult holds the output of the validate action.
type ValidationResult struct {
	Level1Pass bool              `json:"level1_pass"`
	Level2Pass bool              `json:"level2_pass"`
	Level3Pass bool              `json:"level3_pass"`
	Issues     []ValidationIssue `json:"issues"`
}

func executeManageValidate(tree *CapabilityTree, input ManageInput) ManageResult {
	vr := ValidationResult{Level1Pass: true, Level2Pass: true, Level3Pass: true}
	runL1 := input.Level == 0 || input.Level == 1
	runL2 := input.Level == 0 || input.Level == 2
	runL3 := input.Level == 0 || input.Level == 3

	if runL1 {
		issues := validateLevel1(tree)
		if len(issues) > 0 {
			vr.Level1Pass = false
			vr.Issues = append(vr.Issues, issues...)
		}
	}
	if runL2 {
		issues := validateLevel2(tree)
		if len(issues) > 0 {
			vr.Level2Pass = false
			vr.Issues = append(vr.Issues, issues...)
		}
	}
	if runL3 {
		issues := validateLevel3(tree)
		if len(issues) > 0 {
			vr.Level3Pass = false
			vr.Issues = append(vr.Issues, issues...)
		}
	}

	return ManageResult{Action: "validate", Success: true, Data: vr}
}

// validateLevel1 checks per-node self-consistency (§6.3 L1).
func validateLevel1(tree *CapabilityTree) []ValidationIssue {
	var issues []ValidationIssue
	tree.Walk(func(n *CapabilityNode) bool {
		if n.Kind == NodeKindGroup {
			return true
		}
		// L1-1: Summary non-empty
		if n.Prompt == nil || n.Prompt.Summary == "" {
			issues = append(issues, ValidationIssue{Level: 1, NodeID: n.ID, Message: "Prompt.Summary is empty"})
		}
		// L1-2: MinTier valid
		if n.Routing == nil || n.Routing.MinTier == "" {
			issues = append(issues, ValidationIssue{Level: 1, NodeID: n.ID, Message: "Routing.MinTier is empty"})
		} else if tierIndex(n.Routing.MinTier) < 0 {
			issues = append(issues, ValidationIssue{Level: 1, NodeID: n.ID, Message: fmt.Sprintf("Routing.MinTier %q is not a valid tier", n.Routing.MinTier)})
		}
		// L1-3: Non-dynamic nodes must have Runtime.Owner
		if n.Runtime == nil || (!n.Runtime.Dynamic && n.Runtime.Owner == "") {
			issues = append(issues, ValidationIssue{Level: 1, NodeID: n.ID, Message: "Runtime.Owner is empty for non-dynamic node"})
		}
		return true
	})
	return issues
}

// validateLevel2 checks cross-node consistency (§6.3 L2).
func validateLevel2(tree *CapabilityTree) []ValidationIssue {
	var issues []ValidationIssue

	// L2-1: Child MinTier >= parent MinTier
	tree.Walk(func(n *CapabilityNode) bool {
		if n.Kind != NodeKindGroup || n.Routing == nil {
			return true
		}
		parentIdx := tierIndex(n.Routing.MinTier)
		if parentIdx < 0 {
			return true
		}
		for _, childID := range n.Children {
			child := tree.Nodes[childID]
			if child == nil || child.Kind == NodeKindGroup {
				continue
			}
			childMinTier := "task_multimodal"
			if child.Routing != nil && child.Routing.MinTier != "" {
				childMinTier = child.Routing.MinTier
			}
			childIdx := tierIndex(childMinTier)
			if childIdx >= 0 && childIdx < parentIdx {
				issues = append(issues, ValidationIssue{
					Level:   2,
					NodeID:  child.ID,
					Message: fmt.Sprintf("MinTier %q < parent %q MinTier %q", childMinTier, n.ID, n.Routing.MinTier),
				})
			}
		}
		return true
	})

	// L2-2: Dynamic group NamePrefix uniqueness
	prefixMap := make(map[string]string) // prefix → group ID
	for _, g := range tree.DynamicGroups() {
		if g.Runtime == nil || g.Runtime.NamePrefix == "" {
			continue
		}
		if existing, ok := prefixMap[g.Runtime.NamePrefix]; ok {
			issues = append(issues, ValidationIssue{
				Level:   2,
				NodeID:  g.ID,
				Message: fmt.Sprintf("NamePrefix %q overlaps with %q", g.Runtime.NamePrefix, existing),
			})
		}
		prefixMap[g.Runtime.NamePrefix] = g.ID
	}

	return issues
}

// validateLevel3 checks system-level cross-layer consistency (§6.3 L3).
// Note: Some L3 checks require access to runtime state that may not be available
// in this context. We implement what we can with tree-internal data.
func validateLevel3(tree *CapabilityTree) []ValidationIssue {
	var issues []ValidationIssue

	// L3-1: tree.AllStaticTools() vs Registry consistency
	regNames := make(map[string]bool)
	for _, spec := range Registry {
		regNames[spec.ToolName] = true
	}
	treeNames := make(map[string]bool)
	for _, name := range tree.AllStaticTools() {
		treeNames[name] = true
	}
	for name := range regNames {
		if !treeNames[name] {
			issues = append(issues, ValidationIssue{
				Level:   3,
				Message: fmt.Sprintf("Registry tool %q not in tree static tools", name),
			})
		}
	}
	for name := range treeNames {
		if !regNames[name] {
			// Some tools are NOT in Registry — this is expected for runtime-only tools
			// send_email: registered in buildToolDefinitions, not in Registry
			// capability_manage: P4 meta-tool, registered in buildToolDefinitions
			if name != "send_email" && name != "capability_manage" {
				issues = append(issues, ValidationIssue{
					Level:   3,
					Message: fmt.Sprintf("Tree static tool %q not in Registry (may be runtime-only)", name),
				})
			}
		}
	}

	// L3-2: Per-tier allowlist monotonicity
	// Each higher tier must include all tools from lower tiers (minus exclusions)
	for i := 1; i < len(validTiers); i++ {
		lowerTier := validTiers[i-1]
		higherTier := validTiers[i]
		lowerAllow := tree.AllowlistForTier(lowerTier)
		higherAllow := tree.AllowlistForTier(higherTier)
		for name := range lowerAllow {
			if !higherAllow[name] {
				// Check if excluded from the higher tier
				node := tree.LookupByToolHint(name)
				excluded := false
				if node != nil && node.Routing != nil {
					for _, ex := range node.Routing.ExcludeFrom {
						if ex == higherTier {
							excluded = true
							break
						}
					}
				}
				if !excluded {
					issues = append(issues, ValidationIssue{
						Level:   3,
						Message: fmt.Sprintf("Tool %q in %s allowlist but missing from %s (monotonicity violation)", name, lowerTier, higherTier),
					})
				}
			}
		}
	}

	// L3-3: ToolSummaries coverage — every tool/subagent should have a summary
	summaries := tree.ToolSummaries()
	tree.Walk(func(n *CapabilityNode) bool {
		if n.Kind == NodeKindGroup {
			return true
		}
		if _, ok := summaries[n.Name]; !ok {
			issues = append(issues, ValidationIssue{
				Level:   3,
				NodeID:  n.ID,
				Message: fmt.Sprintf("Tool %q has no prompt summary (D1 gap)", n.Name),
			})
		}
		return true
	})

	// L3-4: PolicyGroups — every tool with policy groups should have valid group names
	policyGroups := tree.PolicyGroups()
	for groupName := range policyGroups {
		if !strings.HasPrefix(groupName, "group:") {
			issues = append(issues, ValidationIssue{
				Level:   3,
				Message: fmt.Sprintf("PolicyGroup %q does not follow 'group:*' naming convention", groupName),
			})
		}
	}

	return issues
}

// ---------------------------------------------------------------------------
// P4-5: action=diagnose — Drift diagnosis report
// ---------------------------------------------------------------------------

// DiagnoseResult holds the drift diagnosis output.
type DiagnoseResult struct {
	Inventory string   `json:"inventory"`
	Checks    []string `json:"checks"`
}

func executeManageDiagnose(tree *CapabilityTree) ManageResult {
	var checks []string

	staticCount := len(tree.AllStaticTools())
	dynamicGroups := tree.DynamicGroups()
	groupCount := 0
	tree.Walk(func(n *CapabilityNode) bool {
		if n.Kind == NodeKindGroup && (n.Runtime == nil || !n.Runtime.Dynamic) {
			groupCount++
		}
		return true
	})

	// Build dynamic group summary
	var dynParts []string
	for _, g := range dynamicGroups {
		prefix := ""
		if g.Runtime != nil {
			prefix = g.Runtime.NamePrefix
		}
		dynParts = append(dynParts, prefix)
	}
	sort.Strings(dynParts)
	inventory := fmt.Sprintf("%d static + %d dynamic groups (%s) + %d groups",
		staticCount, len(dynamicGroups), strings.Join(dynParts, "/"), groupCount)

	// D1: prompt summaries alignment
	summaries := tree.ToolSummaries()
	allTools := tree.AllStaticTools()
	d1Aligned := 0
	for _, name := range allTools {
		if _, ok := summaries[name]; ok {
			d1Aligned++
		}
	}
	if d1Aligned == len(allTools) {
		checks = append(checks, fmt.Sprintf("✓ D1 prompt summaries: %d/%d aligned", d1Aligned, len(allTools)))
	} else {
		checks = append(checks, fmt.Sprintf("⚠ D1 prompt summaries: %d/%d aligned (%d missing)", d1Aligned, len(allTools), len(allTools)-d1Aligned))
	}

	// D2: frontend tool policy
	d2ProfileCount := 0
	d2GroupCount := 0
	for _, n := range tree.Nodes {
		if n.Kind == NodeKindGroup || n.Policy == nil {
			continue
		}
		if len(n.Policy.Profiles) > 0 {
			d2ProfileCount++
		}
		if len(n.Policy.PolicyGroups) > 0 {
			d2GroupCount++
		}
	}
	checks = append(checks, fmt.Sprintf("✓ D2 frontend tool policy: %d tools with profiles, %d with policy groups", d2ProfileCount, d2GroupCount))

	// D3: intent allowlists per tier
	tiersOK := 0
	for _, tier := range validTiers {
		allow := tree.AllowlistForTier(tier)
		if allow != nil {
			tiersOK++
		}
	}
	checks = append(checks, fmt.Sprintf("✓ D3 intent allowlists: %d/%d tiers computed", tiersOK, len(validTiers)))

	// D4: frontend tool display coverage
	d4WithDisplay := 0
	d4WithoutDisplay := 0
	for _, n := range tree.Nodes {
		if n.Kind == NodeKindGroup {
			continue
		}
		if n.Display != nil && n.Display.Title != "" {
			d4WithDisplay++
		} else {
			d4WithoutDisplay++
		}
	}
	if d4WithoutDisplay == 0 {
		checks = append(checks, fmt.Sprintf("✓ D4 frontend tool display: %d/%d tools have display specs", d4WithDisplay, d4WithDisplay))
	} else {
		checks = append(checks, fmt.Sprintf("⚠ D4 frontend tool display: %d tools have display, %d missing", d4WithDisplay, d4WithoutDisplay))
	}

	// D5: backend policy groups
	policyGroups := tree.PolicyGroups()
	checks = append(checks, fmt.Sprintf("✓ D5 backend policy groups: %d groups defined", len(policyGroups)))

	// D6: frontend wizard config
	d6WithWizard := 0
	for _, n := range tree.Nodes {
		if n.Kind == NodeKindGroup || n.Policy == nil {
			continue
		}
		if n.Policy.WizardGroup != "" {
			d6WithWizard++
		}
	}
	wizardGroups := tree.WizardGroups()
	checks = append(checks, fmt.Sprintf("✓ D6 frontend wizard config: %d tools assigned to %d wizard groups", d6WithWizard, len(wizardGroups)))

	// D7: display specs
	displaySpecs := tree.DisplaySpecs()
	d7Missing := 0
	for _, name := range allTools {
		if _, ok := displaySpecs[name]; !ok {
			d7Missing++
		}
	}
	if d7Missing == 0 {
		checks = append(checks, fmt.Sprintf("✓ D7 tool display: %d/%d have display specs", len(displaySpecs), len(allTools)))
	} else {
		checks = append(checks, fmt.Sprintf("⚠ D7 tool display: %d/%d missing display specs", d7Missing, len(allTools)))
	}

	// D8: backend policy groups consistency (verify group: prefix convention)
	validGroups := 0
	for groupName := range policyGroups {
		if strings.HasPrefix(groupName, "group:") {
			validGroups++
		}
	}
	checks = append(checks, fmt.Sprintf("✓ D8 policy group naming: %d/%d follow 'group:' convention", validGroups, len(policyGroups)))

	// D9: skill bindings
	bindable := tree.BindableTools()
	checks = append(checks, fmt.Sprintf("✓ D9 skill bindings: %d bindable tools", len(bindable)))

	// Registry vs tree comparison
	regNames := make(map[string]bool)
	for _, spec := range Registry {
		regNames[spec.ToolName] = true
	}
	treeNameSet := make(map[string]bool)
	for _, name := range allTools {
		treeNameSet[name] = true
	}
	var missingFromTree []string
	for name := range regNames {
		if !treeNameSet[name] {
			missingFromTree = append(missingFromTree, name)
		}
	}
	sort.Strings(missingFromTree)
	if len(missingFromTree) > 0 {
		checks = append(checks, fmt.Sprintf("⚠ Missing from tree (in registry): %s", strings.Join(missingFromTree, ", ")))
	} else {
		checks = append(checks, "✓ Registry ⊆ Tree: all registry tools present in tree")
	}

	var missingFromRegistry []string
	for name := range treeNameSet {
		if !regNames[name] {
			missingFromRegistry = append(missingFromRegistry, name)
		}
	}
	sort.Strings(missingFromRegistry)
	if len(missingFromRegistry) > 0 {
		checks = append(checks, fmt.Sprintf("ℹ Tree-only tools (not in registry): %s", strings.Join(missingFromRegistry, ", ")))
	}

	dr := DiagnoseResult{
		Inventory: inventory,
		Checks:    checks,
	}
	return ManageResult{Action: "diagnose", Success: true, Data: dr}
}

// ---------------------------------------------------------------------------
// P4-6: action=generate_prompt — Generate prompt section for a tier
// ---------------------------------------------------------------------------

func executeManageGeneratePrompt(tree *CapabilityTree, input ManageInput) ManageResult {
	if input.Tier == "" {
		return ManageResult{Action: "generate_prompt", Success: false, Error: "tier is required for generate_prompt action"}
	}
	if tierIndex(input.Tier) < 0 {
		return ManageResult{Action: "generate_prompt", Success: false, Error: fmt.Sprintf("invalid tier %q", input.Tier)}
	}

	// Get tools available at this tier
	nodes := tree.ToolsForTier(input.Tier)
	if len(nodes) == 0 {
		return ManageResult{Action: "generate_prompt", Success: true, Data: fmt.Sprintf("(no tools available at tier %q)", input.Tier)}
	}

	// Sort by SortOrder
	type entry struct {
		name    string
		summary string
		order   int
	}
	var entries []entry
	for _, n := range nodes {
		summary := ""
		order := 999
		if n.Prompt != nil {
			summary = n.Prompt.Summary
			order = n.Prompt.SortOrder
		}
		entries = append(entries, entry{name: n.Name, summary: summary, order: order})
	}
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].order != entries[j].order {
			return entries[i].order < entries[j].order
		}
		return entries[i].name < entries[j].name
	})

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("## Tooling (tier: %s)\n\n", input.Tier))
	for _, e := range entries {
		if e.summary != "" {
			sb.WriteString(fmt.Sprintf("- **%s**: %s\n", e.name, e.summary))
		} else {
			sb.WriteString(fmt.Sprintf("- **%s**\n", e.name))
		}
	}

	return ManageResult{Action: "generate_prompt", Success: true, Data: sb.String()}
}

// ---------------------------------------------------------------------------
// P4-7: action=generate_allowlist — Generate tool allowlist for a tier
// ---------------------------------------------------------------------------

func executeManageGenerateAllowlist(tree *CapabilityTree, input ManageInput) ManageResult {
	if input.Tier == "" {
		return ManageResult{Action: "generate_allowlist", Success: false, Error: "tier is required for generate_allowlist action"}
	}
	if tierIndex(input.Tier) < 0 {
		return ManageResult{Action: "generate_allowlist", Success: false, Error: fmt.Sprintf("invalid tier %q", input.Tier)}
	}

	allowlist := tree.AllowlistForTier(input.Tier)
	// Sort for determinism
	names := make([]string, 0, len(allowlist))
	for name := range allowlist {
		names = append(names, name)
	}
	sort.Strings(names)

	result := map[string]interface{}{
		"tier":  input.Tier,
		"count": len(names),
		"tools": names,
	}
	return ManageResult{Action: "generate_allowlist", Success: true, Data: result}
}

// ---------------------------------------------------------------------------
// P4-8: Tool definition for buildToolDefinitions() registration
// ---------------------------------------------------------------------------

// CapabilityManageToolDef returns the llmclient.ToolDef for the capability_manage tool.
// This function is called by attempt_runner.go buildToolDefinitions().
// Note: We return the raw definition components to avoid importing llmclient from capabilities.
func CapabilityManageToolDef() (name, description string, inputSchema json.RawMessage) {
	return "capability_manage",
		"Inspect, diagnose, and manage the capability tree. " +
			"Read actions: tree, inspect, validate, diagnose, generate_prompt, generate_allowlist. " +
			"Write actions: propose_register (propose new node), propose_update (propose field changes), " +
			"propose_routing (propose routing changes), propose_binding (propose skill binding changes), " +
			"apply_patch (apply approved patch, requires exec_escalation).",
		json.RawMessage(`{
  "type": "object",
  "properties": {
    "action": {
      "type": "string",
      "enum": ["tree", "inspect", "validate", "diagnose", "generate_prompt", "generate_allowlist", "propose_register", "propose_update", "propose_routing", "propose_binding", "apply_patch"],
      "description": "The action to perform"
    },
    "node_id": {
      "type": "string",
      "description": "Node ID for inspect/propose_update/propose_routing/propose_binding, or subtree root for tree"
    },
    "depth": {
      "type": "integer",
      "description": "Max depth for tree action (0 = unlimited)"
    },
    "tier": {
      "type": "string",
      "enum": ["greeting", "question", "task_light", "task_write", "task_delete", "task_multimodal"],
      "description": "Intent tier for generate_prompt/generate_allowlist"
    },
    "level": {
      "type": "integer",
      "description": "Validation level for validate: 1 (Node), 2 (Cross-Node), 3 (System), 0 (all)"
    },
    "node_spec": {
      "type": "object",
      "description": "Node specification for propose_register (name, parent, kind, runtime, prompt, routing, perms, skills, display, policy)"
    },
    "updates": {
      "type": "object",
      "description": "Partial fields to update for propose_update (prompt, routing, etc.), NodeRouting for propose_routing, NodeSkillBinding for propose_binding"
    },
    "patch_id": {
      "type": "string",
      "description": "Patch ID for apply_patch"
    },
    "approved": {
      "type": "boolean",
      "description": "Approval flag for apply_patch (requires exec_escalation approval)"
    }
  },
  "required": ["action"]
}`)
}

// ---------------------------------------------------------------------------
// P7-1: action=propose_register — Propose registering a new tool node
// ---------------------------------------------------------------------------

func executeManageProposeRegister(tree *CapabilityTree, input ManageInput) ManageResult {
	if input.NodeSpec == nil {
		return ManageResult{Action: "propose_register", Success: false, Error: "node_spec is required for propose_register"}
	}
	spec := input.NodeSpec
	if spec.Name == "" {
		return ManageResult{Action: "propose_register", Success: false, Error: "node_spec.name is required"}
	}
	if spec.Parent == "" {
		return ManageResult{Action: "propose_register", Success: false, Error: "node_spec.parent is required"}
	}
	if spec.Kind == "" {
		spec.Kind = NodeKindTool
	}

	nodeID := spec.Parent + "/" + spec.Name

	if tree.Lookup(nodeID) != nil {
		return ManageResult{Action: "propose_register", Success: false, Error: fmt.Sprintf("node %q already exists", nodeID)}
	}
	if tree.Lookup(spec.Parent) == nil {
		return ManageResult{Action: "propose_register", Success: false, Error: fmt.Sprintf("parent %q not found", spec.Parent)}
	}

	node := &CapabilityNode{
		ID: nodeID, Name: spec.Name, Kind: spec.Kind, Parent: spec.Parent,
		Runtime: spec.Runtime, Prompt: spec.Prompt, Routing: spec.Routing,
		Perms: spec.Perms, Skills: spec.Skills, Display: spec.Display, Policy: spec.Policy,
	}

	// Fill safe defaults for missing dimensions
	if node.Runtime == nil {
		node.Runtime = &NodeRuntime{Owner: "attempt_runner", EnabledWhen: "always"}
	}
	if node.Prompt == nil {
		node.Prompt = &NodePrompt{Summary: spec.Name + " tool"}
	}
	if node.Routing == nil {
		node.Routing = &NodeRouting{MinTier: "task_write"}
	}
	if node.Perms == nil {
		node.Perms = &NodePermissions{MinSecurityLevel: "allowlist", FileAccess: "none", ApprovalType: "none", ScopeCheck: "none"}
	}
	if node.Skills == nil {
		node.Skills = &NodeSkillBinding{Bindable: true}
	}

	nodeJSON, _ := json.Marshal(node)

	patch := &TreePatch{
		ID:          nextPatchID(),
		Action:      "register",
		Description: fmt.Sprintf("Register new %s %q under %q", spec.Kind, spec.Name, spec.Parent),
		Operations: []PatchOperation{{
			Op: "add", Path: nodeID, Value: nodeJSON,
		}},
		CreatedAt: time.Now().Format(time.RFC3339),
		Status:    "proposed",
	}
	storePatch(patch)
	return ManageResult{Action: "propose_register", Success: true, Data: patch}
}

// ---------------------------------------------------------------------------
// P7-2: action=propose_update — Propose updating node fields
// ---------------------------------------------------------------------------

func executeManageProposeUpdate(tree *CapabilityTree, input ManageInput) ManageResult {
	if input.NodeID == "" {
		return ManageResult{Action: "propose_update", Success: false, Error: "node_id is required for propose_update"}
	}
	if len(input.Updates) == 0 {
		return ManageResult{Action: "propose_update", Success: false, Error: "updates is required for propose_update"}
	}

	node := tree.Lookup(input.NodeID)
	if node == nil {
		node = tree.LookupByName(input.NodeID)
	}
	if node == nil {
		return ManageResult{Action: "propose_update", Success: false, Error: fmt.Sprintf("node %q not found", input.NodeID)}
	}

	var updates ProposeNodeSpec
	if err := json.Unmarshal(input.Updates, &updates); err != nil {
		return ManageResult{Action: "propose_update", Success: false, Error: fmt.Sprintf("invalid updates: %v", err)}
	}

	ops := buildUpdateOps(node, updates)
	if len(ops) == 0 {
		return ManageResult{Action: "propose_update", Success: false, Error: "no updatable fields found in updates"}
	}

	patch := &TreePatch{
		ID:          nextPatchID(),
		Action:      "update",
		Description: fmt.Sprintf("Update %d field(s) on %q", len(ops), node.ID),
		Operations:  ops,
		CreatedAt:   time.Now().Format(time.RFC3339),
		Status:      "proposed",
	}
	storePatch(patch)
	return ManageResult{Action: "propose_update", Success: true, Data: patch}
}

// buildUpdateOps generates PatchOperations for each non-nil dimension in the update spec.
func buildUpdateOps(node *CapabilityNode, updates ProposeNodeSpec) []PatchOperation {
	var ops []PatchOperation
	if updates.Prompt != nil {
		oldJSON, _ := json.Marshal(node.Prompt)
		newJSON, _ := json.Marshal(updates.Prompt)
		ops = append(ops, PatchOperation{Op: "replace", Path: node.ID, Field: "prompt", Value: newJSON, Old: oldJSON})
	}
	if updates.Runtime != nil {
		oldJSON, _ := json.Marshal(node.Runtime)
		newJSON, _ := json.Marshal(updates.Runtime)
		ops = append(ops, PatchOperation{Op: "replace", Path: node.ID, Field: "runtime", Value: newJSON, Old: oldJSON})
	}
	if updates.Routing != nil {
		oldJSON, _ := json.Marshal(node.Routing)
		newJSON, _ := json.Marshal(updates.Routing)
		ops = append(ops, PatchOperation{Op: "replace", Path: node.ID, Field: "routing", Value: newJSON, Old: oldJSON})
	}
	if updates.Perms != nil {
		oldJSON, _ := json.Marshal(node.Perms)
		newJSON, _ := json.Marshal(updates.Perms)
		ops = append(ops, PatchOperation{Op: "replace", Path: node.ID, Field: "perms", Value: newJSON, Old: oldJSON})
	}
	if updates.Skills != nil {
		oldJSON, _ := json.Marshal(node.Skills)
		newJSON, _ := json.Marshal(updates.Skills)
		ops = append(ops, PatchOperation{Op: "replace", Path: node.ID, Field: "skills", Value: newJSON, Old: oldJSON})
	}
	if updates.Display != nil {
		oldJSON, _ := json.Marshal(node.Display)
		newJSON, _ := json.Marshal(updates.Display)
		ops = append(ops, PatchOperation{Op: "replace", Path: node.ID, Field: "display", Value: newJSON, Old: oldJSON})
	}
	if updates.Policy != nil {
		oldJSON, _ := json.Marshal(node.Policy)
		newJSON, _ := json.Marshal(updates.Policy)
		ops = append(ops, PatchOperation{Op: "replace", Path: node.ID, Field: "policy", Value: newJSON, Old: oldJSON})
	}
	return ops
}

// ---------------------------------------------------------------------------
// P7-3: action=propose_routing — Propose routing rule changes
// ---------------------------------------------------------------------------

func executeManageProposeRouting(tree *CapabilityTree, input ManageInput) ManageResult {
	if input.NodeID == "" {
		return ManageResult{Action: "propose_routing", Success: false, Error: "node_id is required for propose_routing"}
	}
	if len(input.Updates) == 0 {
		return ManageResult{Action: "propose_routing", Success: false, Error: "updates (NodeRouting fields) is required for propose_routing"}
	}

	node := tree.Lookup(input.NodeID)
	if node == nil {
		node = tree.LookupByName(input.NodeID)
	}
	if node == nil {
		return ManageResult{Action: "propose_routing", Success: false, Error: fmt.Sprintf("node %q not found", input.NodeID)}
	}

	var newRouting NodeRouting
	if err := json.Unmarshal(input.Updates, &newRouting); err != nil {
		return ManageResult{Action: "propose_routing", Success: false, Error: fmt.Sprintf("invalid routing updates: %v", err)}
	}
	if newRouting.MinTier != "" && tierIndex(newRouting.MinTier) < 0 {
		return ManageResult{Action: "propose_routing", Success: false, Error: fmt.Sprintf("invalid min_tier %q", newRouting.MinTier)}
	}

	oldJSON, _ := json.Marshal(node.Routing)
	newJSON, _ := json.Marshal(&newRouting)

	patch := &TreePatch{
		ID:          nextPatchID(),
		Action:      "routing",
		Description: fmt.Sprintf("Update routing for %q", node.ID),
		Operations: []PatchOperation{{
			Op: "replace", Path: node.ID, Field: "routing", Value: newJSON, Old: oldJSON,
		}},
		CreatedAt: time.Now().Format(time.RFC3339),
		Status:    "proposed",
	}
	storePatch(patch)

	// Generate intent_router.go change suggestion
	var suggestion string
	if len(newRouting.IntentKeywords.ZH) > 0 || len(newRouting.IntentKeywords.EN) > 0 {
		suggestion = fmt.Sprintf(
			"intent_router.go: Tool %q routing updated. IntentKeywords are automatically derived via TreeClassificationKeywords(); no manual code change needed.",
			node.Name,
		)
	}
	if newRouting.MinTier != "" && (node.Routing == nil || newRouting.MinTier != node.Routing.MinTier) {
		tierNote := fmt.Sprintf("MinTier changed to %q — tool will be available from this tier onwards.", newRouting.MinTier)
		if suggestion != "" {
			suggestion += " " + tierNote
		} else {
			suggestion = tierNote
		}
	}

	result := map[string]interface{}{"patch": patch}
	if suggestion != "" {
		result["intent_router_suggestion"] = suggestion
	}
	return ManageResult{Action: "propose_routing", Success: true, Data: result}
}

// ---------------------------------------------------------------------------
// P7-4: action=propose_binding — Propose skill binding changes
// ---------------------------------------------------------------------------

func executeManageProposeBinding(tree *CapabilityTree, input ManageInput) ManageResult {
	if input.NodeID == "" {
		return ManageResult{Action: "propose_binding", Success: false, Error: "node_id is required for propose_binding"}
	}
	if len(input.Updates) == 0 {
		return ManageResult{Action: "propose_binding", Success: false, Error: "updates (NodeSkillBinding fields) is required for propose_binding"}
	}

	node := tree.Lookup(input.NodeID)
	if node == nil {
		node = tree.LookupByName(input.NodeID)
	}
	if node == nil {
		return ManageResult{Action: "propose_binding", Success: false, Error: fmt.Sprintf("node %q not found", input.NodeID)}
	}

	var newBinding NodeSkillBinding
	if err := json.Unmarshal(input.Updates, &newBinding); err != nil {
		return ManageResult{Action: "propose_binding", Success: false, Error: fmt.Sprintf("invalid binding updates: %v", err)}
	}

	oldJSON, _ := json.Marshal(node.Skills)
	newJSON, _ := json.Marshal(&newBinding)

	patch := &TreePatch{
		ID:          nextPatchID(),
		Action:      "binding",
		Description: fmt.Sprintf("Update skill binding for %q", node.ID),
		Operations: []PatchOperation{{
			Op: "replace", Path: node.ID, Field: "skills", Value: newJSON, Old: oldJSON,
		}},
		CreatedAt: time.Now().Format(time.RFC3339),
		Status:    "proposed",
	}
	storePatch(patch)
	return ManageResult{Action: "propose_binding", Success: true, Data: patch}
}

// ---------------------------------------------------------------------------
// P7-5: action=apply_patch — Apply an approved patch to the tree
// ---------------------------------------------------------------------------

func executeManageApplyPatch(tree *CapabilityTree, input ManageInput) ManageResult {
	if input.PatchID == "" {
		return ManageResult{Action: "apply_patch", Success: false, Error: "patch_id is required for apply_patch"}
	}

	patch := loadPatch(input.PatchID)
	if patch == nil {
		return ManageResult{Action: "apply_patch", Success: false, Error: fmt.Sprintf("patch %q not found", input.PatchID)}
	}
	if patch.Status == "applied" {
		return ManageResult{Action: "apply_patch", Success: false, Error: fmt.Sprintf("patch %q already applied", input.PatchID)}
	}

	// P7-11: Approval check — apply_patch requires exec_escalation approval
	if !input.Approved {
		return ManageResult{
			Action:  "apply_patch",
			Success: false,
			Error:   "apply_patch requires exec_escalation approval; set approved=true after obtaining approval",
		}
	}

	// Apply operations to tree under mutation lock.
	// On failure, rebuild the tree from scratch to avoid partial state.
	treeMutationMu.Lock()
	for _, op := range patch.Operations {
		if err := applyOperation(tree, op); err != nil {
			// Rollback: rebuild tree to discard partial modifications
			defaultTree = GenerateTreeFromRegistry()
			treeMutationMu.Unlock()
			return ManageResult{
				Action:  "apply_patch",
				Success: false,
				Error:   fmt.Sprintf("failed to apply operation (op=%s, path=%s): %v; tree rolled back", op.Op, op.Path, err),
			}
		}
	}
	treeMutationMu.Unlock()

	patchStoreMu.Lock()
	patch.Status = "applied"
	patchStoreMu.Unlock()

	// P7-7: Auto-trigger validate L1-L3
	validateResult := executeManageValidate(tree, ManageInput{Level: 0})

	// P7-8: Derivation pipeline regeneration info
	derivation := map[string]string{
		"status":  "in-memory tree updated; derivation targets will reflect changes on next read",
		"action":  "Run 'go generate ./internal/agents/capabilities/...' to regenerate frontend artifacts",
		"targets": "D1(prompt) D3(allowlist) D5(policy) D6(ts) D7(display) D8(wizard) D9(registry)",
	}

	return ManageResult{
		Action:  "apply_patch",
		Success: true,
		Data: map[string]interface{}{
			"patch":      patch,
			"validation": validateResult.Data,
			"derivation": derivation,
		},
	}
}

// applyOperation applies a single PatchOperation to the tree.
func applyOperation(tree *CapabilityTree, op PatchOperation) error {
	switch op.Op {
	case "add":
		var node CapabilityNode
		if err := json.Unmarshal(op.Value, &node); err != nil {
			return fmt.Errorf("unmarshal node for add: %w", err)
		}
		return tree.AddNode(&node)
	case "replace":
		node := tree.Lookup(op.Path)
		if node == nil {
			return fmt.Errorf("node %q not found for replace", op.Path)
		}
		return applyFieldReplace(node, op.Field, op.Value)
	case "remove":
		return tree.RemoveNode(op.Path)
	default:
		return fmt.Errorf("unknown op %q", op.Op)
	}
}

// applyFieldReplace applies a field-level replacement to a node.
func applyFieldReplace(node *CapabilityNode, field string, value json.RawMessage) error {
	switch field {
	case "prompt":
		var v NodePrompt
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		node.Prompt = &v
	case "routing":
		var v NodeRouting
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		node.Routing = &v
	case "runtime":
		var v NodeRuntime
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		node.Runtime = &v
	case "perms":
		var v NodePermissions
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		node.Perms = &v
	case "skills":
		var v NodeSkillBinding
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		node.Skills = &v
	case "display":
		var v NodeDisplay
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		node.Display = &v
	case "policy":
		var v NodePolicy
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		node.Policy = &v
	default:
		return fmt.Errorf("unknown field %q", field)
	}
	return nil
}
