// chrome_profile_decoration.go — Chrome profile UI customization.
//
// Sets the profile name, color, and avatar colors in Chrome's
// Local State and Default/Preferences JSON files so the browser
// window visually identifies which profile is being automated.
//
// Also ensures the "clean exit" flag is set to suppress Chrome's
// "restore pages?" prompt after an unclean shutdown.
//
// TS source: chrome.profile-decoration.ts (198L)
package browser

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

// DecorateOpenAcosmiProfile sets the profile name and color in Chrome's
// Local State and Preferences files.
// Aligns with TS chrome.profile-decoration.ts decorateOpenAcosmiProfile().
func DecorateOpenAcosmiProfile(userDataDir, desiredName, desiredColor string) error {
	if desiredName == "" {
		desiredName = "Crab Claw"
	}
	desiredColor = NormalizeHexColor(desiredColor)
	colorInt := parseHexRgbToSignedArgbInt(desiredColor)

	// --- Local State ---
	localStatePath := filepath.Join(userDataDir, "Local State")
	localState := safeReadJSON(localStatePath)
	if localState == nil {
		localState = make(map[string]any)
	}

	setDeep(localState, []string{"profile", "info_cache", "Default", "name"}, desiredName)
	setDeep(localState, []string{"profile", "info_cache", "Default", "shortcut_name"}, desiredName)
	setDeep(localState, []string{"profile", "info_cache", "Default", "user_name"}, desiredName)
	setDeep(localState, []string{"profile", "info_cache", "Default", "profile_color"}, desiredColor)
	setDeep(localState, []string{"profile", "info_cache", "Default", "user_color"}, desiredColor)
	if colorInt != nil {
		setDeep(localState, []string{"profile", "info_cache", "Default", "profile_color_seed"}, *colorInt)
		setDeep(localState, []string{"profile", "info_cache", "Default", "profile_highlight_color"}, *colorInt)
		setDeep(localState, []string{"profile", "info_cache", "Default", "default_avatar_fill_color"}, *colorInt)
		setDeep(localState, []string{"profile", "info_cache", "Default", "default_avatar_stroke_color"}, *colorInt)
	}

	if err := safeWriteJSON(localStatePath, localState); err != nil {
		return fmt.Errorf("write Local State: %w", err)
	}

	// --- Default/Preferences ---
	prefsPath := filepath.Join(userDataDir, "Default", "Preferences")
	prefs := safeReadJSON(prefsPath)
	if prefs == nil {
		prefs = make(map[string]any)
	}

	setDeep(prefs, []string{"profile", "name"}, desiredName)
	setDeep(prefs, []string{"profile", "profile_color"}, desiredColor)
	setDeep(prefs, []string{"profile", "user_color"}, desiredColor)
	if colorInt != nil {
		setDeep(prefs, []string{"autogenerated", "theme", "color"}, *colorInt)
		setDeep(prefs, []string{"browser", "theme", "user_color2"}, *colorInt)
	}

	if err := safeWriteJSON(prefsPath, prefs); err != nil {
		return fmt.Errorf("write Preferences: %w", err)
	}

	// Write decoration marker.
	markerPath := filepath.Join(userDataDir, ".openacosmi-profile-decorated")
	_ = os.WriteFile(markerPath, []byte(strconv.FormatInt(time.Now().UnixMilli(), 10)+"\n"), 0o644)

	return nil
}

// EnsureProfileCleanExit sets exit_type=Normal and exited_cleanly=true
// to suppress Chrome's "restore pages?" prompt.
// Aligns with TS chrome.profile-decoration.ts ensureProfileCleanExit().
func EnsureProfileCleanExit(userDataDir string) error {
	prefsPath := filepath.Join(userDataDir, "Default", "Preferences")
	prefs := safeReadJSON(prefsPath)
	if prefs == nil {
		prefs = make(map[string]any)
	}

	prefs["exit_type"] = "Normal"
	prefs["exited_cleanly"] = true

	return safeWriteJSON(prefsPath, prefs)
}

// IsProfileDecorated checks if the decoration marker file exists.
func IsProfileDecorated(userDataDir string) bool {
	markerPath := filepath.Join(userDataDir, ".openacosmi-profile-decorated")
	_, err := os.Stat(markerPath)
	return err == nil
}

// --- Helpers ---

// parseHexRgbToSignedArgbInt converts a #RRGGBB hex color to Chrome's
// signed 32-bit ARGB integer format (full opacity alpha = 0xFF).
func parseHexRgbToSignedArgbInt(hex string) *int32 {
	s := strings.TrimSpace(hex)
	if len(s) > 0 && s[0] == '#' {
		s = s[1:]
	}
	if len(s) != 6 {
		return nil
	}
	for _, c := range s {
		if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F')) {
			return nil
		}
	}

	rgb, err := strconv.ParseUint(s, 16, 32)
	if err != nil {
		return nil
	}

	// Prepend full opacity alpha: 0xFF000000 | RGB.
	argbUnsigned := uint32(0xFF000000) | uint32(rgb)
	// Go int32 cast handles the unsigned→signed conversion correctly.
	v := int32(argbUnsigned)
	return &v
}

// safeReadJSON reads and parses a JSON file into a generic map.
// Returns nil if the file doesn't exist or is invalid.
func safeReadJSON(path string) map[string]any {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	var result map[string]any
	if err := json.Unmarshal(data, &result); err != nil {
		return nil
	}
	return result
}

// safeWriteJSON writes a map as formatted JSON to a file.
func safeWriteJSON(path string, data map[string]any) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	b, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, b, 0o644)
}

// setDeep sets a nested value in a generic map using a key path.
// Creates intermediate maps as needed.
func setDeep(obj map[string]any, keys []string, value any) {
	if len(keys) == 0 {
		return
	}
	node := obj
	for _, key := range keys[:len(keys)-1] {
		existing, ok := node[key]
		if ok {
			if m, isMap := existing.(map[string]any); isMap {
				node = m
				continue
			}
		}
		m := make(map[string]any)
		node[key] = m
		node = m
	}
	node[keys[len(keys)-1]] = value
}
